-- MySQL Script generated by MySQL Workbench
-- 12/10/15 19:03:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Anime_Manga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Anime_Manga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Anime_Manga` DEFAULT CHARACTER SET utf8 ;
USE `Anime_Manga` ;

-- -----------------------------------------------------
-- Table `Anime_Manga`.`Anime/Manga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Anime_Manga`.`Anime/Manga` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Generos` VARCHAR(45) NULL,
  `Descrision` VARCHAR(500) NULL,
  `Visto` TINYINT(1) NULL,
  `Fecha` INT NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Anime_Manga`.`Link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Anime_Manga`.`Link` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Pagina` VARCHAR(45) NULL,
  `Url` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `fk_Link_Anime/manga`
    FOREIGN KEY (`Nombre`)
    REFERENCES `Anime_Manga`.`Anime/Manga` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
